# Generated by Django 4.1.5 on 2023-09-13 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カレンダー名')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='開始日時')),
                ('end_dt', models.DateTimeField(verbose_name='終了日時')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.calendar', verbose_name='カレンダー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='読み込み権限')),
                ('write', models.BooleanField(default=False, verbose_name='書き込み権限')),
                ('chat', models.BooleanField(default=False, verbose_name='チャット権限')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.calendar', verbose_name='カレンダー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='share',
            field=models.ManyToManyField(related_name='calendar_share', through='scheduler.CalendarUser', to=settings.AUTH_USER_MODEL, verbose_name='公開範囲'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
